/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedList: typeof import('./src/components/bits/AnimatedList.vue')['default']
    Aurora: typeof import('./src/components/bits/Aurora.vue')['default']
    BlurText: typeof import('./src/components/bits/BlurText.vue')['default']
    ClickSpark: typeof import('./src/components/bits/ClickSpark.vue')['default']
    ClipCard: typeof import('./src/components/ClipCard.vue')['default']
    ClipGrid: typeof import('./src/components/ClipGrid.vue')['default']
    ClipsPane: typeof import('./src/components/settings/ClipsPane.vue')['default']
    ClipsView: typeof import('./src/components/ClipsView.vue')['default']
    CountUp: typeof import('./src/components/bits/CountUp.vue')['default']
    DialogHost: typeof import('./src/components/DialogHost.vue')['default']
    ElasticSlider: typeof import('./src/components/bits/ElasticSlider.vue')['default']
    Folder: typeof import('./src/components/bits/Folder.vue')['default']
    FoldersPane: typeof import('./src/components/settings/FoldersPane.vue')['default']
    GamesBrowser: typeof import('./src/components/GamesBrowser.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IndexingPane: typeof import('./src/components/settings/IndexingPane.vue')['default']
    InfoPane: typeof import('./src/components/settings/InfoPane.vue')['default']
    LibraryView: typeof import('./src/components/LibraryView.vue')['default']
    Magnet: typeof import('./src/components/bits/Magnet.vue')['default']
    PlaybackPane: typeof import('./src/components/settings/PlaybackPane.vue')['default']
    PlayerDetails: typeof import('./src/components/PlayerDetails.vue')['default']
    PlayerOverlay: typeof import('./src/components/PlayerOverlay.vue')['default']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SettingsRow: typeof import('./src/components/settings/SettingsRow.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
    ShinyText: typeof import('./src/components/bits/ShinyText.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SplitText: typeof import('./src/components/bits/SplitText.vue')['default']
    SpotlightCard: typeof import('./src/components/bits/SpotlightCard.vue')['default']
    StarBorder: typeof import('./src/components/bits/StarBorder.vue')['default']
    StatsPane: typeof import('./src/components/settings/StatsPane.vue')['default']
    StoragePane: typeof import('./src/components/settings/StoragePane.vue')['default']
    ThemesPane: typeof import('./src/components/settings/ThemesPane.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    ToastBridge: typeof import('./src/components/ToastBridge.vue')['default']
    TrimBar: typeof import('./src/components/TrimBar.vue')['default']
    UAlert: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContextMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UEmpty: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UFieldGroup: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UKbd: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UProgress: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTooltip: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
